---
title: "Syllabus"
output:
  html_document:
    toc: true
    toc_depth: 3 
---


### Course info
__Instructor__:  
Daniel McDonald  
Office: Myles Brand Hall E210C  
Website: https://dajmcdon.github.io/
Slack: @dajmcdon  
Email: dajmcdon@indiana.edu  

__Office hours__:  
Me: TBA  
Joe: TBA

__Course webpage__:    
WWW: https://stats-432sp2020.github.io/  
Github: https://github.com/stats-432sp2020  
Slack: https://stats-432sp2020.slack.com/

__Lectures__:  
TR 4--5:15, BH 141

__Textbook__:  
Required: [_Advanced Data Analysis from an Elementary Point of View_](https://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/)  
Required: [_Introduction to Statistical Learning_](http://www-bcf.usc.edu/~gareth/ISL/)

__Prerequisite__:  
STAT-S 431 or equivalent or permission of the instructor.


### Course objectives

This is a course in advanced data analysis. Based on the theory of
linear models covered in S431, this course will focus on applying many
types of data analysis methods to interesting datasets. The focus will
be dealing with and describing data rather than on particular methods
per se.

The course combines analysis with methodology and
computational aspects. It treats both the "art" of understanding
unfamiliar data and the "science" of analyzing that data in terms of 
statistical properties. The focus will be on practical aspects of methodology and intuition
to help students develop tools for selecting appropriate methods and
approaches to problems in their own lives. 

I expect that the material should be appropriate and interesting to
students coming from either statistics or informatics/computer
science. I will make an effort to provide necessary background so that
lectures are accessible to both populations.

We will put special emphasis on learning to use certain tools common to companies which actually _do_
data science. This includes [Slack](https://stats-432sp2020.slack.com/), [GitHub](https://github.com/stats-432sp2020), [Rstudio](https://www.rstudio.com), and [Rmarkdown](http://rmarkdown.rstudio.com/). As such, we will
require the use of these technologies.

### Lecture content

Class time will consist of a
combination of lecture, discussion, questions and answers, and problem
solving, with a focus on problem solving. You are strongly encouraged
to bring a laptop to class.

### Textbook

The required textbook for this class is still
in progress, but is excellent. Download it somewhat regularly, as it
is still being updated.

### Course communication

#### Philosophy

This class will use [Slack](https://stats-432sp2020.slack.com/) for class communication. Slack is a Team messaging
app which is frequently adopted by companies and research groups. We will use it for announcements, questions, 
homework communication, etc. You are required to use it. 

Since homework and the project are team-based, you need a way to communicate with your team. Slack is that way. You can
create a special channel for your team. You can direct message individuals. You can message me or the TA. You can post
pictures of cats. The sky is the limit. By using Slack, we will avoid sending lots of email back and forth.

Slack has apps for iPhone or Android, Mac or Windows. Or you can use the web.

If you send me email instead, I may ignore it.

#### Rules

- All content-related (non-personal) questions should be asked in [Slack](https://stats-432sp2020.slack.com/). Use the `general` channel for homework, lecture, or other questions. For personal issues, direct message me (@dajmcdon) or the TA.  
- Before posting a new question please make sure to check if your question has already been answered. Just search.  
- It may be more efficient to answer your question “in-person” so make good use of office hours (2.5 hours per week).  
- Emails will almost certainly be ignored.  
- I generally reply to messages during normal business hours (M-F). My typical response time is 24 hours. Please don't message me on Slack, wait an hour without response, email me, email me again, etc.  
- Ignoring these rules will result in decreased participation points.

### Grading

10 In-class exercises (5 points each)  
10 Reading responses (5 points each)  
6 Homeworks (25 points each)  
1 Course project (PC 1/PC 2/PC 3/Presentation 15/35/75/25)  
2 Take-home exams (150 points each)  


In all cases, a fixed number of points may be __earned__ for each
exercise. Points are not deducted for poor performance in this
class. Points are awarded for excellent performance.


#### In-class exercises

We will regularly have short programming or theoretical exercises during class time. At the end of class, you will push your results to Github for grading. Complete submissions will receive full credit. Partial submissions will receive 2 points. There will be at least 10 of these during the semester. Any submissions you make in excess of 10 will be extra credit.

#### Reading responses

Each chapter will have a short coding exercise which you should submit before we cover the chapter. I will post the exercise on Github, you clone it and upload your changes. These will generally be due before class begins on __Tuesday__ each week. Complete submissions will receive full credit. Partial submissions will receive 2 points. There will be at least 10 of these during the semester. Any submissions you make in excess of 10 will be extra credit.

#### Homeworks

Homework assignments will be completed in groups which I assign. These groups will rotate for each assignment.
Each team will have their own private repository. All assignments will be submitted on Github. Homework grades
will be awarded based on complete and accurate analyses according to the rubric provided with each assignment.
Grades will be adjusted up or down based on participation according to the Github commit messages. You are
expected to consult only with me, the TA, or your assigned group, with the exception of conversations which occur
during class meetings or office hours in the presence of me or the TA. This means that you and your friend (who is in a different group) may not do the homework together.


#### Project

You will be required to complete a team project (2-4 people). You may
choose this group. The goal
is to analyze a dataset in depth using anything that you have learned. The project will have three checkpoints: PC 1 will be due __Thursday, January 25__, PC 2 is due __Thursday, March 8__, PC 3 is due on __Monday, April 30__. All are to be uploaded to your repo by 11:59pm on those dates. See the [project](project.html) page for detailed requirements.

The entire class will give brief presentations during the last week of classes. 

#### Exams

There will be two take home exams. Both will be completed entirely individually. 
The midterm will be made available on __Wednesday, Febuary 21__ for submission by __Wednesday, February 28__.
The second exam will be available __Friday, April 13__ for submission by __Friday, April 20__. In both cases, the exam file will be downloaded from your personal repo at 11:59pm on the due date. Late submissions will not be accepted.

If either of these dates pose some type of problem, you must notify me no later than Friday, January 12. After this date, no alternatives will be considered without medical documentation.

### Important considerations

#### Academic Integrity

As a student at IU, you are expected to adhere to the standards and
policies detailed in the [Code of Student Rights, Responsibilities, and Conduct](http://www.iu.edu/~code/). When you submit an
assignment with your name on it, 
you are signifying that the work contained therein is yours, unless
otherwise cited or referenced. Any ideas or materials taken from
another source for either written or oral use must be fully
acknowledged. If you are unsure about the expectations for completing
an assignment or taking a test or exam, be sure to seek clarification
beforehand. All suspected violations of the Code will be handled
according to University policies. Sanctions for academic misconduct
may include a failing grade on the assignment, reduction in your final
course grade, a failing grade in the course, among other
possibilities, and must include a report to the Dean of Students, who
may impose additional disciplinary sanctions. 
 
#### Note Selling

Several commercial services have approached students regarding
selling class notes/study guides to their classmates. Please be
advised that selling a faculty member’s notes/study guides
individually or on behalf of one of these services using IU email,
Canvas, or Oncourse violates both IU information technology and IU
intellectual property policy. Selling the faculty member’s
notes/study guides to fellow students in this course is not
permitted. Violations of this policy will be considered violations of
the Code of Student Rights, Responsibilities, and Conduct and will be
reported to the Dean of Students as a violation of course rules
(academic misconduct). Sanctions for academic misconduct may include
a failing grade on the assignment for which the notes/study guides
are being sold, a reduction in your final course grade, a failing
grade in the course, among other possibilities. 

#### Solutions

Some of the problems that are assigned are similar or identical to those assigned in previous years
by me or other instructors for this or other courses. Using proofs or
code from anywhere other than the textbooks (with attribution), this
year's course notes (with attribution), or the course website is not
only considered cheating 
(as described above), it is easily detectable cheating. Such behavior is strictly forbidden.

#### Cheating

In previous years, I have caught students cheating on the exams. I did not enforce any penalty because the action did not help. Cheating, in my experience, occurs because students don't understand the material, so the result is usually a failing grade even before I impose any penalty and report the incident to the Dean's office. I carefully structure exams to make it so that I can catch these issues. I __will__ catch you, and it does not help. Do your own work, and use the TA and me as resources. If you are struggling, we are here to help.

_If I suspect cheating, your case will be forwarded to the Dean's office. No questions asked._

#### Title IX

As your instructor, one of my responsibilities is to help create a safe learning environment on our campus. Title IX and our own Sexual Misconduct policy prohibit sexual misconduct. If you have experienced sexual misconduct, or know someone who has, the University can help. If you are seeking help and would like to speak to someone confidentially, you can make an appointment with The Sexual Assault Crisis Service (SACS) at 812-855-8900; Counseling and Psychological Services (CAPS) at 812-855-5711; Confidential Victim Advocates (CVA) at 812-856-2469; or the IU Health Center at 812-855-4011. More information about available resources can be found at [here](http://stopsexualviolence.iu.edu/help/index.html). It is also important that you know that federal regulations and University policy require me to promptly convey any information about potential sexual misconduct known to me to our campus’s Deputy Title IX Coordinator or IU’s Title IX Coordinator. In that event, they will work with a small number of others on campus to ensure that appropriate measures are taken and resources are made available to the student who may have been harmed. Protecting a student’s privacy is of utmost concern, and all involved will only share information with those that need to know to ensure the University can respond and assist. I encourage you to visit http://stopsexualviolence.iu.edu to learn more.
